### ISSUE TITLE
I installed strimzi kafka(directly from strimzi.io) and later I installed operator and jaegar (from here),everything is running perfectly but  Kafka-producer and Kafka-consumer is crashing constantly

### ISSUE THREAD

**Issue by 5olitude** [gkoenig/strimzi-jaeger-eval#6]
***logs of kafka producer
------------------------
User=0.02s Sys=0.01s Real=0.04s
Exception in thread "main" java.lang.NumberFormatException: Cannot parse null string
	at java.base/java.lang.Integer.parseInt(Integer.java:630)
	at java.base/java.lang.Integer.parseInt(Integer.java:786)
	at KafkaProducerConfig.fromEnv(KafkaProducerConfig.java:39)
	at KafkaProducerExample.main(KafkaProducerExample.java:23)
**************************************************************************
***logs of kafka consumer 
 -----------------------
n thread "main" org.apache.kafka.common.config.ConfigException: Invalid value null for configuration key.deserializer: must be non-null.
	at org.apache.kafka.clients.consumer.ConsumerConfig.appendDeserializerToConfig(ConsumerConfig.java:615)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:666)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:647)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:627)

Is it necessary to have a kafka bridge to connect to jaeger ? whether I'm doing something wrong

**Comment by 5olitude** [comment]
Actually I wasn't using the correct name space , and the Jaegar is still using open tracing apis deprecated by cloud native computing foundation later upgraded  to openTelemtry , so anyone using this method to collect traces will work fine as of now , Strimzi community officially announced they will close the support by July 2023 and move to openTelemetry   for tracing .
